window.PARTICIPANTS = [
    "Aadidev Soni",
    "Aaradhana",
    "Abhijeet",
    "Achyuta Keshawam Dixit",
    "Aditi Sachin Pawar",
    "Aditi Sahu",
    "Aditya Vijay Mishra",
    "Aditya Vikram Surve",
    "Ajay Kumar",
    "Akarsh Narang",
    "Akshay Naphade",
    "Aman Raghuvanshi",
    "Ananya Garg",
    "Anika Nitin Kanade",
    "Ankita Gupta",
    "Anmol Rastogi",
    "Anukrati Chaturvedi",
    "Arav Shah",
    "Archita Verma",
    "Aryesh Gouraha",
    "Ashish Pandey",
    "Astitva Yadav",
    "Ayush Kumar Chaubey",
    "Bhumi Atish Mor",
    "Chetan Disania",
    "Chhavi",
    "Darryl Bryn Elizabeth Suresh",
    "Deepanjli Sharma",
    "Devangee Jain",
    "Dhairya Vijay",
    "Dhananjay Agrawal",
    "Dhritiman Roy",
    "Dhruv Verma",
    "Divyansh Tejaswi",
    "Divyansh Verma",
    "Eva Chaudhari",
    "Gargi Chandrakant Bharambe",
    "Gaurav Gaisenn",
    "Gaurav Kiran Patil",
    "Gouri Saxena",
    "Harguneet Singh",
    "Harshit Gupta",
    "Harshpreet Kaur",
    "Hiten Kakkar",
    "Isha Vinesh Bhirud",
    "Ishant Singh",
    "Ishika Gupta",
    "Ishita Pandey",
    "Jayant Chaudhary",
    "Jaydatta Rajesh Kadam",
    "Kapse Piyush Vijay",
    "Kavyanshi Jain",
    "Kelvi Baraiya",
    "Krishna Goyal",
    "Kritarth Prasad",
    "Mallepally Sri Varsha",
    "Manjiri Umeshkumar Tayde",
    "Mayuresh Mahajan",
    "Miriyala Hitesh Chandra",
    "Mohammed Ehsaan",
    "Mrudula Mulay",
    "Nayan Lakshmi Sajan",
    "Neha Kishor Aher",
    "Nikhil Hari Bhosle",
    "Om Himthani",
    "Pallavi Kumari",
    "Prachi Deepak Guddemane",
    "Prachi Singh",
    "Pragati Budholiya",
    "Prashasti Singhal",
    "Pratham Devadiga",
    "Pratichi Jain",
    "Pratik Lokhande",
    "Pratiksha Kulkarni",
    "Pratyush Singh",
    "Prerna Suman",
    "Prithvi Chandak",
    "Prithviraj Rajput",
    "Priyanshi Sai",
    "Rashmi Nagora",
    "Revan Masanam",
    "Rishab Satpathy",
    "Rishi Saheb Padalwar",
    "Rishika Singhai",
    "Rohit Zunzunwala",
    "Sahajvir Singh Sokhi",
    "Sanidhya Jain",
    "Sanskruti Dhaneshkumar Mishra",
    "Sara Santosh Deshpande",
    "Sarthak Singh",
    "Shivam Parihar",
    "Shourya Jain",
    "Shrushti Sachin Tawani",
    "Singhania Divyam Pareshkumar",
    "Soumya Gupta",
    "Sri Sarayu Anugu",
    "Srimuralikrishna Venkatapathi Jandhyala",
    "Sudha Kruthi Bodapati",
    "Tarang Nanwatkar",
    "Tejaswi Yamani",
    "Utkarsh Sharma",
    "Vansh Bagree",
    "Vansh Harish Somkuwar",
    "Vedant Sanjay Bhagat",
    "Venkat Edupuganti",
    "Vihaan Mahesh Polkam",
    "Vishal Rajagopal",
    "Yash Agrawal"
];
